module.exports = {
  __esModule: true,
  default: {},
  Gradient: () => () => null,
  Truncate: () => () => null,
  tint: () => '#000000',
  hexa: () => 'rgba(0,0,0,0)',
  Shadow: {},
  Transition: {},
  zIndex: {},
  fontStack: () => () => null,
  monoStack: () => () => null,
  Spinner: () => null,
  Label: () => null,
  PrefixLabel: () => null,
  Input: () => null,
  TextArea: () => null,
  UnderlineInput: () => null,
  H1: () => null,
  H2: () => null,
  H3: () => null,
  H4: () => null,
  H5: () => null,
  H6: () => null,
  P: () => null,
  Span: () => null,
  FlexRow: () => null,
  FlexCol: () => null,
  Onboarding: () => () => null,
  HorizontalRule: () => null,
};
